# Generated by Django 3.1.1 on 2020-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asisten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_asisten', models.CharField(max_length=50)),
            ],
        ),
    ]
