# Generated by Django 3.1.1 on 2020-10-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mata_kuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_matkul', models.CharField(max_length=100, null=True)),
                ('semester', models.CharField(max_length=50)),
                ('islab', models.CharField(default='0', max_length=2)),
            ],
        ),
    ]
