# Generated by Django 3.1.1 on 2020-10-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0002_mata_kuliah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_group', models.CharField(max_length=100, null=True)),
                ('semester', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
