# Generated by Django 3.1.1 on 2020-10-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_ruangan', models.CharField(max_length=100, null=True)),
                ('kapasitas', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waktu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulai', models.CharField(max_length=100, null=True)),
                ('berakhir', models.CharField(max_length=50, null=True)),
                ('hari', models.CharField(max_length=50, null=True)),
                ('islab', models.BooleanField(default=False)),
            ],
        ),
    ]
