# Generated by Django 3.1.1 on 2020-09-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0003_auto_20200926_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='asisten',
            name='kode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='asisten',
            name='nama',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='asisten',
            name='nama_asisten',
            field=models.CharField(default='', max_length=100),
        ),
    ]
