# Generated by Django 3.1.1 on 2020-09-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0004_auto_20200926_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asisten',
            name='kode',
        ),
        migrations.RemoveField(
            model_name='asisten',
            name='nama',
        ),
    ]
