# Generated by Django 3.1.1 on 2020-10-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0004_ruangan_waktu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asisten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_asisten', models.CharField(max_length=100, null=True)),
                ('nim', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
