# Generated by Django 3.1.1 on 2020-10-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0005_asisten'),
    ]

    operations = [
        migrations.CreateModel(
            name='MengajarByDosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.dosen')),
                ('id_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.mata_kuliah')),
            ],
        ),
    ]
