# Generated by Django 3.1.1 on 2020-10-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0006_mengajarbydosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='id_dosen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='no_hp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
