# Generated by Django 3.1.1 on 2020-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0007_auto_20200926_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_hari', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruangan', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
