# Generated by Django 3.1.1 on 2020-10-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0008_mengajarbyasisten'),
    ]

    operations = [
        migrations.AddField(
            model_name='mata_kuliah',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
