# Generated by Django 3.1.1 on 2020-10-25 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0009_mata_kuliah_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asisten',
            old_name='nm_asisten',
            new_name='nama_asisten',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='nm_group',
            new_name='nama_group',
        ),
        migrations.RenameField(
            model_name='ruangan',
            old_name='nm_ruangan',
            new_name='nama_ruangan',
        ),
    ]
