# Generated by Django 3.1.1 on 2020-10-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0010_auto_20201025_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
