# Generated by Django 3.1.1 on 2020-10-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0011_group_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='id_dosen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
