# Generated by Django 3.1.1 on 2020-10-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0012_auto_20201027_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asisten',
            name='nim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='no_hp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mata_kuliah',
            name='semester',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='kapasitas',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
