# Generated by Django 3.1.1 on 2020-10-29 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0013_auto_20201027_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MengajarByAsisten',
            new_name='AsistenByMatkul',
        ),
        migrations.RenameModel(
            old_name='MengajarByDosen',
            new_name='DosenByMatkul',
        ),
        migrations.CreateModel(
            name='GroupByMatkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.group')),
                ('id_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penjadwalan.mata_kuliah')),
            ],
            options={
                'verbose_name': 'GriupByMatkul',
                'verbose_name_plural': 'GriupByMatkuls',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
