# Generated by Django 3.1.1 on 2020-10-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjadwalan', '0014_auto_20201029_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupbymatkul',
            options={'managed': True, 'verbose_name': 'GroupByMatkul', 'verbose_name_plural': 'GroupByMatkul'},
        ),
    ]
